//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskJournal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskJournal()
        {
            this.UserTasks = new HashSet<UserTasks>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid homeId { get; set; }
        public System.DateTime date { get; set; }
        public System.Guid taskId { get; set; }
    
        public virtual Home Home { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTasks> UserTasks { get; set; }
    }
}
