//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTasks
    {
        public System.Guid userId { get; set; }
        public System.Guid taskId { get; set; }
        public System.DateTime dateStart { get; set; }
        public bool isDone { get; set; }
        public Nullable<System.DateTime> dateDone { get; set; }
        public string resilt { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual TaskJournal TaskJournal { get; set; }
    }
}
